---
title: "Project2"
author: "Noah Bean, Alec Behrendt, Jeff Fong, George Paul"
date: "2023-02-15"
output: html_document
---

# Libraries
```{r}
library(class)
library(janitor)
library(neuralnet)
```

# Load & Clean Data
```{r}
tele <- read.csv("tele.csv")
str(tele)
summary(tele)
```
```{r}
#Remove index and duration variables, factorize categorical variables
#A
tele$X <- NULL
tele$job <- as.factor(tele$job)
tele$marital <- as.factor(tele$marital)
tele$education <- as.factor(tele$education)
tele$default <- as.factor(tele$default)
tele$housing <- as.factor(tele$housing)
tele$loan <- as.factor(tele$loan)
#B
tele$contact <- as.factor(tele$contact)
tele$month <- as.factor(tele$month)
tele$day_of_week <- as.factor(tele$day_of_week)
tele$duration <- NULL
#C
tele$poutcome <- as.factor(tele$poutcome)
#D
tele$y <- as.factor(tele$y)
```
```{r}
#Normalize numeric variables
normalize <- function(x) {
  return ( (x - min(x)) / (max(x) - min(x)) )
}
tele$age <- normalize(tele$age)
tele$campaign <- normalize(tele$campaign)
tele$pdays <- normalize(tele$pdays)
tele$previous <- normalize(tele$previous)
tele$emp.var.rate <- normalize(tele$emp.var.rate)
tele$cons.price.idx <- normalize(tele$cons.price.idx)
tele$cons.conf.idx <- normalize(tele$cons.conf.idx)
tele$euribor3m <- normalize(tele$euribor3m)
tele$nr.employed <- normalize(tele$nr.employed)
```

# Train/Test Data
```{r}
n <- nrow(tele)
set.seed(0)
idx <- sample(n, .7*n)
tele.train <- tele[idx,]
tele.test <- tele[-idx,]
```

# KNN
```{r}
#Create dfs of only numeric variables
tele.knn.train <- tele.train[,c(1,11:13,15:19)]
tele.knn.test <- tele.test[,c(1,11:13,15:19)]

#Run model
tele.knn.preds <- ifelse(knn(tele.knn.train, tele.knn.test, cl = tele.train$y, k = 5) == "yes", 1, 0)
table(tele.knn.preds)
```

# ANN
```{r, cache=T}
#Building model matrix for neuralnet
tele.ann <- as.data.frame(model.matrix(~ .-1 , data = tele))
tele.ann <- clean_names(tele.ann)
tele.ann <- as.data.frame(lapply(tele.ann, normalize))

#Rebuild train/test
tele.ann.train <- tele.ann[idx,]
tele.ann.test <- tele.ann[-idx,]

nn.model <- neuralnet(yyes ~ ., data = tele.ann.train, hidden = 3, stepmax = 1e+8)
#Identify observations with success probability of at least 1/6
tele.ann.preds <- ifelse(predict(nn.model, tele.ann.test) > 1/6, 1, 0)
```

# Logistic Regression
```{r}
tele.logreg <- glm(y~., data=tele.train, family="binomial")
#Backward step selection to select variables
tele.logreg2 <- step(tele.logreg, direction="backward")
#Identify observations with success probability of at least 1/6
logreg.preds <- ifelse(predict(tele.logreg2, tele.test, type = "response") > 1/6, 1, 0)
```

# Combined Prediction
```{r}
#Majority rule combined prediction
combined_preds <- ifelse(tele.knn.preds + tele.ann.preds + logreg.preds >= 2, 1, 0)
```